Update cowspeak

diff --git a/cowspeak/usr/bin/cowspeak b/cowspeak/usr/bin/cowspeak
--- a/cowspeak/usr/bin/cowspeak
+++ b/cowspeak/usr/bin/cowspeak
@@ -2,71 +2,77 @@
 # Written by Sourav Goswami
 # The GNU General Public License v3.0
 
-help = ->{
-puts <<EOF
-Hi, my name is cowspeak. I speak a quote on your terminal.
+coloured, blink = true, false
+# Check if the output should colourized
+if ARGV.include?('--no-colour') or ARGV.include?('-nc')
+	ARGV.delete('--no-colour')
+	ARGV.delete('-nc')
+	coloured = false
+end
 
-Usage: Run me from the command line without any arguments, and I will show you a fortune.
-
-Pass me some arguments:
-	Available arguments are:
-	--art or -a                     Display a tutorial on adding your own art.
-	--blink or -b			Blink the texts (not supported in all terminals yet).
-	--documentation or -d           Display the whole documentation including this help.
-	--download or -dl		Download missing files and database from Github.
-	--file= or -f=			Specify the ASCII file path to display your own ASCII art.
-	--fortune			Show a fortune without any art.
-	--help or -h                    Display this help.
-	--manual or -m                  Display a manual. Same as documentation.
-	--no-colour or -nc		No RGB colour.
-	--read or -r=                   Read a file.
-	--rotate-colour or -rc		Rotate the RGB colours.
-	--text= or -t=                  Display a custom text.
-
-This is the help page, for more help with examples, run #{__FILE__} --documentation or #{__FILE__} -d
-EOF
-exit! 0
-}
-
-exception_handle = ->(error) {
-	puts "Uh oh! Sorry, #{__FILE__} Crashed."
-	print "Select one of the following:
-		1. Exit.
-		2. Show the usage (#{__FILE__} -h)
-		3. Show Error Details.
-		4. Save Error Details to a Log File.
-		- Default: 1 (Exit).
-		-> Choose: "
-
-	case STDIN.gets.to_i
-		when 1 then exit!
-		when 2 then help.call
-		when 3 then puts error ; exit! 125
-		when 4 then
-			File.open('/tmp/cowspeak-log.txt', 'a+') do |log_file|
-				log_file.puts("\n#{Time.new.strftime('Error on %D at %T')} => \n\t#{error}")
-				puts 'The error has been written to /tmp/cowspeak-log.txt'
-			end
-			exit! 126
-		else exit!
-	end
-}
-
-blink = false
+# Check if the output should be blinked
 if ARGV.include?('--blink') or ARGV.include?('-b')
+	ARGV.delete('--blink')
+	ARGV.delete('-b')
 	blink = true
 	at_exit do puts "\033[0m" end
 end
 
-coloured = true
-coloured = false if ARGV.include?('--no-colour') or ARGV.include?('-nc')
-
+# Check if the colour should be rotated in each line
 rotate_colour = false
-rotate_colour = true if ARGV.include?('--rotate-colour')  or ARGV.include?('-rc')
+if ARGV.include?('--rotate-colour')  or ARGV.include?('-rc')
+	ARGV.delete('--rotate_colour')
+	ARGV.delete('-rc')
+	rotate_colour = true
+end
 
-if ARGV.include?('--documentation') or ARGV.include?('-d') or ARGV.include?('--manual') or ARGV.include?('-m')
-puts <<EOF
-Hi, my name is cowspeak. I speak a quote on your terminal.
+chars = ->(string) do
+	if coloured
+		characters = string.split("\n")
+		selected_colours = [(196..200), (202..207), (208..213), (82..87), (40..45), (214..219), (112..117), (138..159), (74..87), (112..123),
+		 [34, 35, 36, 37, 38, 39, 174, 175, 179, 180, 181] ].sample.to_a
+
+		selected_colour_array = selected_colours
+		selected_colour_array = [selected_colours, selected_colours.reverse].sample
+
+		for c in characters
+			index = 0
+			for i in (0..c.length - 1) do
+				index += 1 if (i % (c.length/(selected_colour_array.length)) == 0) unless i == 0 || c.length <= selected_colour_array.length
+				index = selected_colour_array.size - 1 if index >= selected_colour_array.size
+
+				print "\033[5m" if blink
+				print("\033[38;5;#{selected_colour_array[index]}m#{c[i]}\033[0m")
+			end
+			puts
+			selected_colour_array.rotate! if rotate_colour
+			selected_colour_array.shift if selected_colour_array.length > 3
+		end
+	else
+		print "\033[5m" if blink
+		print string, "\n"
+	end
+end
+
+# Exit if no tty is detected
+unless STDOUT.tty?
+	chars.call("Sorry, No terminal found...")
+	chars.call("Run this is a proper terminal (gnome-terminal, xfce4-terminal, konsole, terminology, terminator, terminix, xterm, and so on...)")
+	chars.call("Also make sure you have ncurses installed (required for calculating number of columns to draw the output)")
+	chars.call("Thank you for downloading #{__FILE__.split('/').last}. Run #{__FILE__.split('/').last} --help or #{__FILE__.split('/').last} -h for more details")
+	exit 156
+end
+
+# Don't run the program if the terminal width is too small (atleast 32 is needed for default arts)
+until %x(tput cols).to_i > 31
+	sleep 0.1
+	printf "\033[H\033[J"
+	chars.call('The terminal is too narrow. Please make it bigger')
+end
+
+help = ->{
+chars.call(
+"Hi, my name is cowspeak. I speak a quote on your terminal.
 
 Usage: Run me from the command line without any arguments, and I will show you a fortune.
 
@@ -77,12 +83,44 @@ Pass me some arguments:
 	--documentation or -d           Display the whole documentation including this help.
 	--download or -dl		Download missing files and database from Github.
 	--file= or -f=			Specify the ASCII file path to display your own ASCII art.
-	--fortune			Show a fortune without any art.
 	--help or -h                    Display this help.
 	--manual or -m                  Display a manual. Same as documentation.
-	--no-colour or -nc		No RGB colour.
+	--no-art or -na			Don't display the animal.
+	--net -r -n			Get data from a webisite (in curl format).
+	--no-colour or -nc		Don't colourize the output.
 	--read or -r=                   Read a file.
-	--rotate-colour or -rc		Rotate the RGB colours.
+	--rotate-colour or -rc		Rotate the output colours in each line.
+	--text= or -t=                  Display a custom text.
+
+This is the help page, for more help with examples, run #{__FILE__} --documentation or #{__FILE__} -d")
+exit! 0
+}
+
+if ARGV.include?('--documentation') or ARGV.include?('-d') or ARGV.include?('--manual') or ARGV.include?('-m')
+ARGV.delete('--documentation')
+ARGV.delete('-d')
+ARGV.delete('--manual')
+ARGV.delete('-m')
+
+chars.call(
+"Hi, my name is cowspeak. I speak a quote on your terminal.
+
+Usage: Run me from the command line without any arguments, and I will show you a fortune.
+
+Pass me some arguments:
+	Available arguments are:
+	--art or -a                     Display a tutorial on adding your own art.
+	--blink or -b			Blink the texts (not supported in all terminals yet).
+	--documentation or -d           Display the whole documentation including this help.
+	--download or -dl		Download missing files and database from Github.
+	--file= or -f=			Specify the ASCII file path to display your own ASCII art.
+	--help or -h                    Display this help.
+	--manual or -m                  Display a manual. Same as documentation.
+	--net -r -n			Get data from a webisite (in curl format).
+	--no-art or -na			Don't display the animal.
+	--no-colour or -nc		Don't colourize the output.
+	--read or -r=                   Read a file.
+	--rotate-colour or -rc		Rotate the output colours in each line.
 	--text= or -t=                  Display a custom text.
 
 		Examples:
@@ -98,25 +136,34 @@ Pass me some arguments:
 			To read a file from the storage:
 				#{__FILE__} --read='path/file.extension' or #{__FILE__} -r='path/file.extension'
 
-			NOTE: --text with --read or -t with -r will not read the file, but show the custom text.
-					Here's the priority of them, the higher the priority, the higher chances they are considered.
-						Priority 1: text
-						Priority 2: read
+			Pipe another program's output to cowspeak (also accepts arguments):
+				echo hello | #{__FILE__}
+				echo hello | #{__FILE__} --argument -short_argument
+
+			To read from the internet in curl format:
+				#{__FILE__} --net=http://www.example.net
+				#{__FILE__} --net=http://www.example.net --argument -short_argument
+
 	Help:
 		#{__FILE__} -h or --help for the help message.
-		#{__FILE__} --documentation or #{__FILE__} -d for this documentation.
+		#{__FILE__} -d or --documentation or --manual or -m for this documentation.
 	Creating Custom Art:
 		You can make your own art. Run #{__FILE__} --art or #{__FILE__} -a for more information.
-	Update Fortune Database:
-		This is just an extra feature. Update synchronizes your fortunes.data with https://raw.githubusercontent.com/bmc/fortunes/master/fortunes.
-		You need not to update the database for months. It's fine if you never update the database. There are many fun inside the provided database.
-		However, if the database gets deleted, run #{__FILE__} --update or #{__FILE__} -u. You can occasionally run an update - won't harm anything.
-EOF
+	Update Download all the files:
+		If you are missing some files, then please take a moment to download all the files from Github.
+		To do that, run:
+			cowspeak --download or -d
+			It will download all the necessary files. This may download 5 MB files from the internet.
+			NOTE: This argument will write files to /usr/share/cowspeak/ directory.
+				     This may need root privilege to do that.")
 exit! 0
 end
 
+# Show a user friendly tutorial on how to add arts
 if ARGV.include?('--art') or ARGV.include?('-a')
-puts <<EOF
+ARGV.delete('--art')
+ARGV.delete('-a')
+puts "
 You can create your own art. Here's a short introduction on how to do that:
 	1. Create an empty document in your computer with 'art' extension (myart.art).
 	2. Edit the document and Type your name in the first line. If you copy someone's work, provide the artist's name.
@@ -140,14 +187,49 @@ You can create your own art. Here's a short introduction on how to do that:
 	- For more examples, look at other files.
 	- You can use other files. By default they are located in /usr/share/cowspeak/arts/
 	- To use your custom art, just run #{__FILE__} --file='your_art.art'
-	- If it's located in another directory then #{__FILE__} --file='directory/your_art.art'
-EOF
+	- If it is located in another directory then #{__FILE__} --file='directory/your_art.art'
+"
 exit! 0
 end
 
-help.call if ARGV.include?('--help') or ARGV.include?('-h')
+# Take exceptions very very seriously. Handle them very gently.
+exception_handle = ->(error) {
+	puts "Uh oh! Sorry, #{__FILE__} has Encountered an Error."
+	print "Select one of the following:
+		1. Exit.
+		2. Show the usage (#{__FILE__} -h)
+		3. Show Error Details.
+		4. Save Error Details to a Log File.
+		5. Contact Developer
+		- Default: 1 (Exit).
+		-> Choose: "
+
+	case STDIN.gets.to_i
+		when 2 then help.call
+		when 3 then puts error ; exit! 125
+		when 4
+			File.open('/tmp/cowspeak-log.txt', 'a+') do |log_file|
+				log_file.puts("\n#{Time.new.strftime('Error on %D at %T')} => \n\t#{error}")
+				puts 'The error has been written to /tmp/cowspeak-log.txt'
+			end
+			exit! 128
+		when 5
+			puts "Please contact <souravgoswami@protonmail.com>"
+			puts "Tell him about #{error} in #{__FILE__}"
+		else exit! 127
+	end
+}
+
+if ARGV.include?('--help') or ARGV.include?('-h')
+	ARGV.delete('--help')
+	ARGV.delete('-h')
+	help.call
+end
 
 if ARGV.include?('--download') or ARGV.include?('-dl')
+	ARGV.delete('--download')
+	ARGV.delete('-dl')
+
 	begin
 		require 'net/http'
 
@@ -218,52 +300,28 @@ if ARGV.include?('--download') or ARGV.include?('-dl')
 	end
 end
 
-if ARGV.include?('--fortune')
-	begin
-		puts File.read('/usr/share/cowspeak/fortunes.data').split("\n%\n").sample
-	rescue Exception => e
-		exception_handle.call(e)
-	end
-	exit
+show_art = true
+if ARGV.include?('--no-art') || ARGV.include?('-na')
+	ARGV.delete('--no-art')
+	ARGV.delete('-na')
+	show_art = false
 end
 
 begin
-	chars = ->(string) {
-			if coloured
-				chars = string.split("\n")
-				selected_colours = [ (196..200), (202..207), (208..213), (82..87), (40..45), (214..219), (112..117) ].sample.to_a
-				selected_colour_array = [selected_colours, selected_colours.reverse].sample
+	file = ARGV.select { |a| a.start_with?('--file') || a.start_with?('-f') }
+	file.each do |arg| ARGV.delete(arg) end
 
-				for c in chars
-					index = 0
-					for i in (0..c.length - 1) do
-						index += 1 if (i % (c.length/(selected_colour_array.length)) == 0) unless i == 0 || c.length <= selected_colour_array.length
-						index = selected_colour_array.size - 1 if index >= selected_colour_array.size
-
-						print "\033[5m" if blink
-						print("\033[38;5;#{selected_colour_array[index]}m#{c[i]}\033[0m")
-					end
-					puts
-					selected_colour_array.rotate! if rotate_colour
-					selected_colour_array.shift if selected_colour_array.length > 3
-				end
+	unless file[-1].nil?
+		if file[-1].split('=')[1]
+			unless file.empty? then file = file[-1].split('=')[1]
+				else file = "/usr/share/cowspeak/arts/#{%w(cow.art squirrels.art killer_squirrels.art).sample}" end
 		else
-			print string, "\n"
+				file = "/usr/share/cowspeak/arts/#{%w(cow.art squirrels.art killer_squirrels.art).sample}"
 		end
-	}
-
-	all_chars = ''
-	count, i, init, init_length = 0, 0, "=" * (%x(tput cols).to_i/2), (%x(tput cols ).to_i/2)
-	arg1, arg2, arg3 = [], [], []
-	arg1 = ARGV[0].split('=').map(&:chomp) unless ARGV[0].nil?
-	arg2 = ARGV[1].split('=').map(&:chomp) unless ARGV[1].nil?
-	arg3 = ARGV[2].split('=').map(&:chomp) unless ARGV[2].nil?
-
-	if %w(--file -f).include? arg1[0] then file = arg1[1]
-		elsif %w(--file -f).include? arg2[0] then file = arg2[1]
-		elsif %w(--file -f).include? arg3[0] then file = arg3[1]
-		else file = "/usr/share/cowspeak/arts/#{%w(cow.art squirrels.art killer_squirrels.art).sample}"
+	else
+			file = "/usr/share/cowspeak/arts/#{%w(cow.art squirrels.art killer_squirrels.art).sample}"
 	end
+
 	unless File.file?(file)
 		puts 'Looks like the art file doesn\'t exist'
 		puts "Type #{__FILE__} --help or #{__FILE__} -h for help"
@@ -271,34 +329,95 @@ begin
 		exit! 127
 	end
 
-	if %w(--text -t).include? arg1[0] then text = arg1[1]
-	elsif %w(--text -t).include? arg2[0] then text = arg2[1]
-	elsif %w(--text -t).include? arg3[0] then text = arg3[1]
+	text = ''
+	pipe = false
 
-	elsif %w(--read -r).include? arg1[0]
-		if File.exist?(arg1[1]) then text = File.read(arg1[1]).gsub("\n", ' ') else puts "File Doesn't exist. #{__FILE__} -h for more help" ; exit! 127 end
-	elsif %w(--read -r).include? arg2[0]
-		if File.exist?(arg2[1]) then text = File.read(arg2[1]).gsub("\n", ' ') else puts "File Doesn't exist. #{__FILE__} -h for more help" ; exit! 127 end
-	elsif %w(--read -r).include? arg3[0]
-		if File.exist?(arg3[1]) then text = File.read(arg3[1]).gsub("\n", ' ') else puts "File Doesn't exist. #{__FILE__} -h for more help" ; exit! 127 end
-	else text = File.read('/usr/share/cowspeak/fortunes.data').split("\n%\n").sample.gsub("\n", ' ')
+	# Check if pipe and output is redicred from another program, waste 0.000001 seconds on gets if not
+	require 'timeout'
+	begin
+		Timeout::timeout 0.000001 do pipe = STDIN.gets end
+	rescue Timeout::Error
 	end
 
-	all_chars += ' //' + init + "\\\\\n"
-	text.each_char do |c|
-		all_chars += count == 0 ? "|| #{c}" : "#{c}"
-		count += 1
-		i += 1
-		if (count >= init_length - 10 and c == " ") or i == text.length or count == init_length
-			all_chars += " " * (init_length - count + 1) + "||" + "\n"
-			count = 0
+	# if pipe is passed, read the ouput maximum for 5 full seconds. Else, read fortunes.
+	if pipe
+		text += pipe
+		begin
+			Timeout::timeout 5 do
+				loop do
+					val = STDIN.gets
+					break if val.nil?
+					text += val
+				end
+			end
+		rescue Timeout::Error
 		end
 	end
 
-	all_chars += ' \\\\' + init + "//\n"
-	a = File.readlines(file)[2..-1]
-	think = %w[. o O].sample
-	all_chars += "  " * a.length + think * 3 + "\n" + "  " * a.length + think * 2 + "\n" + "  " * a.length + think + "\n" + a.join
+	if text.empty?
+		text = ARGV.select { |t| t.start_with?('--text=') or t.start_with?('-t=') }
+		text.each do |arg| ARGV.delete(arg) end
+
+		unless text.empty? then text= text[-1].split('=')[1] end
+		text = File.read('/usr/share/cowspeak/fortunes.data').split("\n%\n").sample if text.nil? or text.empty?
+
+		read = ARGV.select { |r| r.start_with?('--read=') || r.start_with?('-r=') }
+		read.each do |arg| ARGV.delete(arg) end
+
+		unless read.empty?
+			f = read[-1].split('=')[1]
+			unless f.nil?
+				text = File.read(f) if File.exists?(f)
+			end
+		end
+
+		net = ARGV.select { |n| n.start_with?('--net=') or n.start_with?('-n=') }
+		net.each do |arg| ARGV.delete(arg) end
+
+		unless net.empty?
+			uri = net[-1].split('=')[1]
+			unless uri.nil?
+				begin
+					require 'net/http'
+					text = Net::HTTP.get(URI(uri))
+				rescue Errno::ECONNREFUSED
+					puts "Failed to open the URL. Please Make sure you have mentioned the protocol"
+					puts "Example:\n\thttp://www.example.net"
+					exit! 1
+				rescue SocketError
+					puts "Failed to read the URL. Please make sure you have an active internet connection."
+					exit! 2
+				rescue Exception
+					puts "Sorry an error occurred while trying to open #{uri}"
+					exit! 126
+				end
+			end
+		end
+	end
+
+	all_chars = ''
+
+	if show_art
+		text = text.gsub("\n", ' ')
+		count, i, init, init_length = 0, 0, "=" * (%x(tput cols).to_i/2), (%x(tput cols ).to_i/2)
+		all_chars += ' //' + init + "\\\\\n"
+		text.each_char do |c|
+			all_chars += count == 0 ? "|| #{c}" : "#{c}"
+			count += 1
+			i += 1
+			if (count >= init_length - 10 and c == " ") or i == text.length or count == init_length
+				all_chars += " " * (init_length - count + 1) + "||" + "\n"
+				count = 0
+			end
+		end
+
+		all_chars += ' \\\\' + init + "//\n"
+		a = File.readlines(file)[2..-1]
+		think = %w[. o O].sample
+		all_chars += "  " * a.length + think * 3 + "\n" + "  " * a.length + think * 2 + "\n" + "  " * a.length + think + "\n" + a.join
+	else
+		all_chars = text
+	end
 
 	chars.call(all_chars)
 
